/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-10-25 17:18:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.DamniduIT22602978;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Header2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1696690298000L));
    _jspx_dependants.put("jar:file:/E:/SLIIT/thirdsem/OOP/EventPlan_JavaServlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/EventPlan/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<!--boxicons-->\r\n");
      out.write("<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("\r\n");
      out.write("    <!--css-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"DamniduIT22602978/css/stylesheetT1.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <title>Event Aliens</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!--NAV-->\r\n");
      out.write("    <nav class=\"navT\" id=\"navT\">\r\n");
      out.write("        <div class=\"navTmenu container\" id=\"navT-menu\">\r\n");
      out.write("            <div class=\"navTshape\"></div>\r\n");
      out.write("            <div class=\"navTclose\" id=\"navT-close\">\r\n");
      out.write("                <i class='bx bxs-left-arrow' ></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"navTdata\">\r\n");
      out.write("                \r\n");
      out.write("                <span class=\"navTgreeting\">Hi,</span>\r\n");
      out.write("                <h1 class=\"navTname\">");
      out.print(session.getAttribute("username") );
      out.write("</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("                <ul class=\"navTlist\">\r\n");
      out.write("                    <li class=\"navTitem\">\r\n");
      out.write("                        <a href=\"#home\" class=\"navTlink active-link\">\r\n");
      out.write("                            <i class='bx bxs-home-heart' ></i>Home\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"navTitem\">\r\n");
      out.write("                        <a href=\"DamniduIT22602978/Profile.jsp\" class=\"navTlink \">\r\n");
      out.write("                            <i class='bx bxs-user' ></i>Profile \r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"navTitem\">\r\n");
      out.write("                        <a href=\"#packages\" class=\"navTlink active-link\">\r\n");
      out.write("                            <i class='bx bxs-briefcase-alt-2'></i>Packages   \r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"navTitem\">\r\n");
      out.write("                        <a href=\"#About\" class=\"navTlink active-link\">\r\n");
      out.write("                            <i class='bx bx-bookmark-heart' ></i>About Us\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"navTitem\">\r\n");
      out.write("                        <a href=\"#gallery\" class=\"navTlink active-link\">\r\n");
      out.write("                            <i class='bx bx-folder'></i>Gallery\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"navTitem\">\r\n");
      out.write("                        <a href=\"#team\" class=\"navTlink active-link\">\r\n");
      out.write("                            <i class='bx bx-group'></i> Team \r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"navTitem\">\r\n");
      out.write("                        <a href=\"#reviews\" class=\"navTlink active-link\">\r\n");
      out.write("                            <i class='bx bxs-message-square-dots'></i>Reviews\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("               <div class=\"navTsignin \" id=\"navT-signin\">\r\n");
      out.write("                <a href=\"login.jsp\">\r\n");
      out.write("	\r\n");
      out.write("                    <button >Log Out<i class='bx bxs-log-out-circle' ></i></button></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--main-->\r\n");
      out.write("    <main class=\"mainT\" id=\"mainT\">\r\n");
      out.write("        <!--header-->\r\n");
      out.write("        <header class=\"headerT\" id=\"headerT\">\r\n");
      out.write("           <nav class=\"headerTnav container\">\r\n");
      out.write("            <a href=\"#\" class=\"headerTlogo\">\r\n");
      out.write("                ExquisiteEvent\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"headerTtoggle\" id=\"headerT-toggle\">\r\n");
      out.write("                <i class='bx bxs-right-arrow' ></i>\r\n");
      out.write("            </div>\r\n");
      out.write("           </nav> \r\n");
      out.write("        </header>\r\n");
      out.write("        <section class=\"sectionT container \" id=\"home\">\r\n");
      out.write("            <div class=\"swiper mySwiper1\">\r\n");
      out.write("                <div class=\"swiper-wrapper\">\r\n");
      out.write("                <div class=\"swiper-slide\"><img src=\"DamniduIT22602978/img/event1.jpg\" alt=\"img1\">\r\n");
      out.write("                <div class=\"inputone\" >\r\n");
      out.write("                    <h1>Wedding Occasions</h1>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        You can Recieve the Hotels For Your Specail day \r\n");
      out.write("                        So,Come and Do your specail day memorable.!\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div> </div>\r\n");
      out.write("                <div class=\"swiper-slide\"><img src=\"DamniduIT22602978/img/event 2.jpg\" alt=\"img2\">\r\n");
      out.write("                    <div class=\"inputone\" >\r\n");
      out.write("                        <h1>Socials</h1>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            You can Recieve us For Your Specail Social Events \r\n");
      out.write("                            So,Come and Do your specail day memorable.!\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div></div>\r\n");
      out.write("                <div class=\"swiper-slide\"><img src=\"DamniduIT22602978/img/event3.jpg\" alt=\"img3\">\r\n");
      out.write("                    <div class=\"inputone\" >\r\n");
      out.write("                        <h1>Conference Meetings</h1>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            You can Recieve Us For Your Specail Conference Meetings \r\n");
      out.write("                            So,Come and Succes Your day.!\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div></div>\r\n");
      out.write("                <div class=\"swiper-slide\"><img src=\"DamniduIT22602978/img/event4.jpg\" alt=\"img4\">\r\n");
      out.write("                    <div class=\"inputone\" >\r\n");
      out.write("                        <h1>Birthday celebrations </h1>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            You can Recieve Us For Your Birthday celebrations \r\n");
      out.write("                            So,Come and happy your Loving Ones.!\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div></div>\r\n");
      out.write("                <div class=\"swiper-slide\"><img src=\"DamniduIT22602978/img/event5.jpg\" alt=\"img5\">\r\n");
      out.write("                    <div class=\"inputone\" >\r\n");
      out.write("                        <h1>Musical Festivals</h1>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            You can Recieve Us And Success Your Event\r\n");
      out.write("                            So,Come and Do your specail day memorable.!\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div></div>\r\n");
      out.write("                <div class=\"swiper-slide\"><img src=\"DamniduIT22602978/img/event6.jpg\" alt=\"img6\">\r\n");
      out.write("                    <div class=\"inputone\" >\r\n");
      out.write("                        <h1>Dinner Dance</h1>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            You can Recieve the Hotels For Your Specail day \r\n");
      out.write("                            So,Come and Do your specail day memorable.!\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div></div>\r\n");
      out.write("                <div class=\"swiper-slide\"><img src=\"DamniduIT22602978/img/event7.jpg\" alt=\"img7\">\r\n");
      out.write("                    <div class=\"inputone\" >\r\n");
      out.write("                        <h1>Special Occasions</h1>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            You can Recieve the Hotels For Your Specail day \r\n");
      out.write("                            So,Come and Do your specail day memorable.!\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write("        <section class=\"sectionT container sectionTheight\" id=\"packages\">\r\n");
      out.write("            <h1>Packages</h1>\r\n");
      out.write("            <div class=\"swiper mySwiper2\">\r\n");
      out.write("                <div class=\"swiper-wrapper\">\r\n");
      out.write("                <div class=\"swiper-slide\">\r\n");
      out.write("                <div class=\"inputone1\" ><img src=\"DamniduIT22602978/img/event4.jpg\" alt=\"img4\">\r\n");
      out.write("                    <h1>Wedding Packages</h1>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        You can Recieve the <br>Hotels For Your Specail day \r\n");
      out.write("                        So,Come and Do your <br>specail day memorable.!\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div> </div>\r\n");
      out.write("                <div class=\"swiper-slide\">\r\n");
      out.write("                    <div class=\"inputone1\" ><img src=\"DamniduIT22602978/img/event4.jpg\" alt=\"img4\">\r\n");
      out.write("                        <h1>Socials Package</h1>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            You can Recieve the <br>Hotels For Your Specail day \r\n");
      out.write("                            So,Come and Do your <br>specail day memorable.!\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div></div>\r\n");
      out.write("                <div class=\"swiper-slide\">\r\n");
      out.write("                    <div class=\"inputone1\" ><img src=\"DamniduIT22602978/img/event4.jpg\" alt=\"img4\">\r\n");
      out.write("                        <h1>Photography Packages</h1>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            You can Recieve the <br>Hotels For Your Specail day \r\n");
      out.write("                            So,Come and Do your <br>specail day memorable.!\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div></div>\r\n");
      out.write("                <div class=\"swiper-slide\">\r\n");
      out.write("                    <div class=\"inputone1\" ><img src=\"DamniduIT22602978/img/event4.jpg\" alt=\"img4\">\r\n");
      out.write("                        <h1>Birthday celebrations Packages </h1>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            You can Recieve the <br>Hotels For Your Specail day \r\n");
      out.write("                            So,Come and Do your <br>specail day memorable.!\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div></div>\r\n");
      out.write("                <div class=\"swiper-slide\">\r\n");
      out.write("                    <div class=\"inputone1\" ><img src=\"DamniduIT22602978/img/event4.jpg\" alt=\"img4\">\r\n");
      out.write("                        <h1>Catering Packages</h1>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            You can Recieve the <br>Hotels For Your Specail day \r\n");
      out.write("                            So,Come and Do your <br>specail day memorable.!\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div></div>\r\n");
      out.write("                <div class=\"swiper-slide\">\r\n");
      out.write("                    <div class=\"inputone1\" ><img src=\"DamniduIT22602978/img/event4.jpg\" alt=\"img4\">\r\n");
      out.write("                        <h1>Dinner Dance Packages</h1>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            You can Recieve the <br>Hotels For Your Specail day \r\n");
      out.write("                            So,Come and Do your <br>specail day memorable.!\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div></div>\r\n");
      out.write("                <div class=\"swiper-slide\">\r\n");
      out.write("                    <div class=\"inputone1\" ><img src=\"DamniduIT22602978/img/event4.jpg\" alt=\"img4\">\r\n");
      out.write("                        <h1>Special Occasions Packages</h1>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            You can Recieve the <br>Hotels For Your Specail day \r\n");
      out.write("                        So,Come and Do your <br>specail day memorable.!\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"sectionT container \" id=\"About\">\r\n");
      out.write("            <h1>ABOUT</h1>\r\n");
      out.write("            <div class=\"swiper\">\r\n");
      out.write("                <div class=\"about-containt\">\r\n");
      out.write("                   <div class=\"about-img\">\r\n");
      out.write("                    <img src=\"DamniduIT22602978/img/event4.jpg\" alt=\"img4\">\r\n");
      out.write("                    <form action=\"\" method=\"post\">\r\n");
      out.write("                        <input type=\"submit\" value=\"Contact Us\">\r\n");
      out.write("                    </form>\r\n");
      out.write("                   </div>\r\n");
      out.write("                   <div class=\"containt\">\r\n");
      out.write("                    <h1>We Will Make Your Special Day Memorable!</h1>\r\n");
      out.write("                    <p>gdjdkdkdnnd shsjkkdndbsjdkdkdddlklsldddk jhsksdnsdkdksdds \r\n");
      out.write("                        ghjsdksdksdlkdsldllds sjsdksdkdsldslldlsd sksdkklsdldsldsl\r\n");
      out.write("                        gdjdkdkdnnd shsjkkdndbsjdkdkdddlklsldddk jhsksdnsdkdksdds \r\n");
      out.write("                        ghjsdksdksdlkdsldllds sjsdksdkdsldslldlsd sksdkklsdldsldsl\r\n");
      out.write("                        gdjdkdkdnnd shsjkkdndbsjdkdkdddlklsldddk jhsksdnsdkdksdds \r\n");
      out.write("                        ghjsdksdksdlkdsldllds sjsdksdkdsldslldlsd sksdkklsdldsldsl\r\n");
      out.write("                        gdjdkdkdnnd shsjkkdndbsjdkdkdddlklsldddk jhsksdnsdkdksdds \r\n");
      out.write("                        ghjsdksdksdlkdsldllds sjsdksdkdsldslldlsd sksdkklsdldsldsl\r\n");
      out.write("                        gdjdkdkdnnd shsjkkdndbsjdkdkdddlklsldddk jhsksdnsdkdksdds \r\n");
      out.write("                        ghjsdksdksdlkdsldllds sjsdksdkdsldslldlsd sksdkklsdldsldsl\r\n");
      out.write("\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"sectionT container sectionTheight\" id=\"gallery\">\r\n");
      out.write("            <h1>GALLERY</h1>\r\n");
      out.write("            <div class=\"swiper mySwiper3\">\r\n");
      out.write("                <div class=\"swiper-wrapper\">\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                    <img src=\"DamniduIT22602978/img/event5.jpg\" alt=\"img5\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"swiper-slide\">\r\n");
      out.write("                    <img src=\"DamniduIT22602978/img/event5.jpg\" alt=\"img5\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"swiper-slide\">\r\n");
      out.write("                    <img src=\"DamniduIT22602978/img/event5.jpg\" alt=\"img5\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"swiper-slide\">\r\n");
      out.write("                    <img src=\"DamniduIT22602978/img/event5.jpg\" alt=\"img5\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"swiper-slide\">\r\n");
      out.write("                    <img src=\"DamniduIT22602978/img/event5.jpg\" alt=\"img5\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"swiper-slide\">\r\n");
      out.write("                    <img src=\"DamniduIT22602978/img/event5.jpg\" alt=\"img5\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"sectionT container sectionTheight\" id=\"team\">\r\n");
      out.write("            <h1>TEAM</h1>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"sectionT container sectionTheight\" id=\"reviews\">\r\n");
      out.write("            <h1>REVIEWS</h1>\r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </main>\r\n");
      out.write("    <!--main js-->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"DamniduIT22602978/Js/Main2.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
