/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-10-25 15:07:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.DamniduIT22602978;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class success_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1696690298000L));
    _jspx_dependants.put("jar:file:/E:/SLIIT/thirdsem/OOP/EventPlan_JavaServlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/EventPlan/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Inform page</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"DamniduIT22602978/css/additional_data.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div id=\"slide\">\r\n");
      out.write("            <div class=\"item\" style=\"background-image: url(DamniduIT22602978/img/1.jpg);\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"name\"><h2>Hotel Details</h2>Reservation ID:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDetails}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </div>\r\n");
      out.write("                    <div class=\"des\">\r\n");
      out.write("                    <form action=\"HotelinfoInsert\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" id=\"reserveid\" name=\"reserveId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDetails}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    <label for=\"hotel id\">Hotel Id:</label><br>\r\n");
      out.write("  					<select id=\"hotel_id\" name=\"hotel_id\">\r\n");
      out.write("					  <option value=\"H001\">H001</option>\r\n");
      out.write("					  <option value=\"H002\">H002</option>\r\n");
      out.write("					  <option value=\"H003\">H003</option>\r\n");
      out.write("					  <option value=\"H004\">H004</option>\r\n");
      out.write("					  <option value=\"H005\">H005</option>\r\n");
      out.write("						</select><br>\r\n");
      out.write("                    <label for=\"attendees\">No of attendees:</label><br>\r\n");
      out.write("  					<input type=\"text\" id=\"attendees\" name=\"attendees\"><br>\r\n");
      out.write("  					<label for=\"halltype\">Hall Type:</label><br>\r\n");
      out.write("  					<select id=\"halltype\" name=\"halltype\">\r\n");
      out.write("					  <option value=\"ballroom\">Ballroom</option>\r\n");
      out.write("					  <option value=\"Conference\">Conference Room</option>\r\n");
      out.write("					  <option value=\"Meeting\">Meeting Room</option>\r\n");
      out.write("					  <option value=\"Banquet-Hall\">Banquet Hall</option>\r\n");
      out.write("					  <option value=\"Outdoor\">Outdoor Trace OR Garden</option>\r\n");
      out.write("					  <option value=\"Bar\">Lounge Or Cocktail Bar</option>\r\n");
      out.write("					  <option value=\"Auditorium\">Auditorium</option>\r\n");
      out.write("					  <option value=\"Pool\">Pool Area</option>\r\n");
      out.write("						</select><br>\r\n");
      out.write("					<label for=\"specialrqst\">Any Further Details:</label><textarea id=\"specilarqst\" name=\"Specialrqst\"  rows=\"3\" cols=\"20\" placeholder=\"Further Details\"></textarea><br>\r\n");
      out.write("                    <input class=\"buttonT\"type=\"submit\" value=\"Submit\">\r\n");
      out.write("                    </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\" style=\"background-image: url(DamniduIT22602978/img/2.jpg);\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"name\"><h2>Decorations Details</h2>Reservation ID:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDetails}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                    <div class=\"des\">\r\n");
      out.write("                    <form action=\"DecorationinfoInsert\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" id=\"reserveid\" name=\"reserveId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDetails}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    <label for=\"Decorator id\">Event Decorator Id:</label><br>\r\n");
      out.write("  					<select id=\"Decorator_id\" name=\"Decorator_id\">\r\n");
      out.write("					  <option value=\"D001\">D001</option>\r\n");
      out.write("					  <option value=\"D002\">D002</option>\r\n");
      out.write("					  <option value=\"D003\">D003</option>\r\n");
      out.write("					  <option value=\"D004\">D004</option>\r\n");
      out.write("					  <option value=\"D005\">D005</option>\r\n");
      out.write("						</select><br>\r\n");
      out.write("                    <label for=\"attendees\">No of attendees:</label><br>\r\n");
      out.write("  					<input type=\"text\" id=\"attendees\" name=\"attendees\"><br>\r\n");
      out.write("  					<label for=\"eventtype\">Event Type:</label><br>\r\n");
      out.write("  					<select id=\"eventtype\" name=\"eventtype\">\r\n");
      out.write("					  <option value=\"birthday\">Birthday</option>\r\n");
      out.write("					  <option value=\"wedding\">Wedding</option>\r\n");
      out.write("					  <option value=\"Cooperate\">Cooperate Event</option>\r\n");
      out.write("						</select><br>\r\n");
      out.write("						<label for=\"eventtheme\">Event Theme:</label><br>\r\n");
      out.write("  					<input type=\"text\" id=\"eventtheme\" name=\"eventtheme\"><br>\r\n");
      out.write("						<label for=\"decorationstyle\">Decoration Style:</label><br>\r\n");
      out.write("  					<select id=\"decorationstyle\" name=\"decorationstyle\">\r\n");
      out.write("					  <option value=\"rustic\">Rustic</option>\r\n");
      out.write("					  <option value=\"modern\">Modern</option>\r\n");
      out.write("					  <option value=\"vintage\">Vintage</option>\r\n");
      out.write("						</select><br>\r\n");
      out.write("					<label for=\"specialrqst\">Any Further Details:</label><textarea id=\"specilarqst\" name=\"Specialrqst\"  rows=\"3\" cols=\"20\" placeholder=\"Further Details\"></textarea><br>\r\n");
      out.write("                    <input class=\"buttonT\"type=\"submit\" value=\"Submit\">\r\n");
      out.write("                    </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\" style=\"background-image: url(DamniduIT22602978/img/3.jpg);\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"name\"><h2>Catering</h2>Reservation ID:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDetails}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                    <div class=\"des\">\r\n");
      out.write("                    <form action=\"CateringInfo\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" id=\"reserveid\" name=\"reserveId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDetails}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    <label for=\"catering id\">Catering Service  Id:</label><br>\r\n");
      out.write("  					<select id=\"catering_id\" name=\"catering_id\">\r\n");
      out.write("					  <option value=\"C001\">C001</option>\r\n");
      out.write("					  <option value=\"C002\">C002</option>\r\n");
      out.write("					  <option value=\"C003\">C003</option>\r\n");
      out.write("					  <option value=\"C004\">C004</option>\r\n");
      out.write("					  <option value=\"C005\">C005</option>\r\n");
      out.write("						</select><br>\r\n");
      out.write("                    <label for=\"attendees\">No of attendees:</label><br>\r\n");
      out.write("  					<input type=\"text\" id=\"attendees\" name=\"attendees\"><br>\r\n");
      out.write("  					<label for=\"eventtype\">Event Type:</label><br>\r\n");
      out.write("  					<select id=\"eventtype\" name=\"eventtype\">\r\n");
      out.write("					  <option value=\"birthday\">Birthday</option>\r\n");
      out.write("					  <option value=\"wedding\">Wedding</option>\r\n");
      out.write("					  <option value=\"Cooperate\">Cooperate Event</option>\r\n");
      out.write("						</select><br>\r\n");
      out.write("						<label for=\"eventtheme\">Event Theme:</label><br>\r\n");
      out.write("  					<input type=\"text\" id=\"eventtheme\" name=\"eventtheme\"><br>\r\n");
      out.write("  					<label for=\"fooditem\">Food items:</label><br><textarea id=\"fooditem\" name=\"fooditem\"  rows=\"1\" cols=\"20\" placeholder=\"Enter Food Items\"></textarea><br>\r\n");
      out.write("						<label for=\"platetype\">Plate type:</label><br>\r\n");
      out.write("  					<select id=\"platetype\" name=\"platetype\">\r\n");
      out.write("					  <option value=\"premium\">Premium</option>\r\n");
      out.write("					  <option value=\"luxury\">Luxury</option>\r\n");
      out.write("					  <option value=\"normal\">Normal</option>\r\n");
      out.write("						</select><br>\r\n");
      out.write("					<label for=\"specialrqst\">Any Further Details:</label><textarea id=\"specilarqst\" name=\"Specialrqst\"  rows=\"3\" cols=\"20\" placeholder=\"Further Details\"></textarea><br>\r\n");
      out.write("                    <input class=\"buttonT\"type=\"submit\" value=\"Submit\">\r\n");
      out.write("                    </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\" style=\"background-image: url(DamniduIT22602978/img/4.jpg);\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"name\"><h2>Photography</h2>Reservation ID:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDetails}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                    <div class=\"des\">\r\n");
      out.write("                   <form action=\"Photographinfo\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" id=\"reserveid\" name=\"reserveId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDetails}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    <label for=\"Photographer id\">Photographer Id:</label><br>\r\n");
      out.write("  					<select id=\"Photographer_id\" name=\"Photographer_id\">\r\n");
      out.write("					  <option value=\"P001\">P001</option>\r\n");
      out.write("					  <option value=\"P002\">P002</option>\r\n");
      out.write("					  <option value=\"P003\">P003</option>\r\n");
      out.write("					  <option value=\"P004\">P004</option>\r\n");
      out.write("					  <option value=\"P005\">P005</option>\r\n");
      out.write("						</select><br>\r\n");
      out.write("                    <label for=\"attendees\">No of attendees:</label><br>\r\n");
      out.write("  					<input type=\"text\" id=\"attendees\" name=\"attendees\"><br>\r\n");
      out.write("  					<label for=\"Packagetype\">Package Type:</label><br>\r\n");
      out.write("  					<select id=\"packagetype\" name=\"packagetype\">\r\n");
      out.write("					  <option value=\"golden\">Golden</option>\r\n");
      out.write("					  <option value=\"premium\">Premium</option>\r\n");
      out.write("					  <option value=\"silver\">Silver</option>\r\n");
      out.write("						</select><br>\r\n");
      out.write("						<label for=\"eventtheme\">Event Theme:</label><br>\r\n");
      out.write("  					<input type=\"text\" id=\"eventtheme\" name=\"eventtheme\"><br>\r\n");
      out.write("  					<label for=\"vidoegrapher\">Videographer:</label><br>\r\n");
      out.write("  					<input type=\"radio\" id=\"videographerY\" name=\"videographer\" value=\"yes\">\r\n");
      out.write("					  <label for=\"vidoegrapherY\">Need</label>\r\n");
      out.write("					  <input type=\"radio\" id=\"videographerN\" name=\"videographer\" value=\"no\">\r\n");
      out.write("					  <label for=\"vidoegrapherN\">No Need</label><br>\r\n");
      out.write("					<label for=\"specialrqst\">Any Further Details:</label><textarea id=\"specilarqst\" name=\"Specialrqst\"  rows=\"3\" cols=\"20\" placeholder=\"Further Details\"></textarea><br>\r\n");
      out.write("                    <input class=\"buttonT\"type=\"submit\" value=\"Submit\">\r\n");
      out.write("                    </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"buttons\">\r\n");
      out.write("            <button id=\"prev\"><i class=\"fa-solid fa-angle-left\"></i></button>\r\n");
      out.write("            <button id=\"next\"><i class=\"fa-solid fa-angle-right\"></i></button>\r\n");
      out.write("            <form action=\"ViewEvent\" method=\"post\">\r\n");
      out.write("             <input type=\"hidden\" id=\"reserveid\" name=\"reserveId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDetails}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            <input type=\"submit\" value=\"View Final\" id=\"Done\">\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"DamniduIT22602978/Js/additional_data.js\"></script>\r\n");
      out.write("</body> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
